= Ldap

Ldap servers -> https://en.wikipedia.org/wiki/List_of_LDAP_software[List of LDAP software - from wikipedia]

Use `https://jumpcloud.com/blog/choosing-ldap-server[Choosing the Right LDAP Server]` or `https://medium.com/geekculture/the-only-guide-you-need-to-get-started-with-ldap-6f526385934f[The only guide you need to get started with LDAP]` to get inspiration to pick Ldap server.

- https://azure.microsoft.com/en-us/products/active-directory/[Microsoft Azure Active Directory Server]
- https://directory.apache.org[Apache Directory Server]
- https://www.openldap.org[OpenLDPA]
- https://directory.fedoraproject.org/[389 Directory Server]
- https://www.freeipa.org/page/Main_Page[FreeIPA]

https://www.saashub.com/compare-apacheds-vs-openldap?ref=compare[Compare Apache Directory vs OpenLDAP]


== Microsoft Azure Active Directory Server

----
Azure Active Directory Domain Services (Azure AD DS) provides managed domain services such as domain join, group policy, lightweight directory access protocol (LDAP), and Kerberos/NTLM authentication. You use these domain services without the need to deploy, manage, and patch domain controllers (DCs) in the cloud.

An Azure AD DS managed domain lets you run legacy applications in the cloud that can't use modern authentication methods, or where you don't want directory lookups to always go back to an on-premises AD DS environment. You can lift and shift those legacy applications from your on-premises environment into a managed domain, without needing to manage the AD DS environment in the cloud.

Azure AD DS integrates with your existing Azure AD tenant. This integration lets users sign in to services and applications connected to the managed domain using their existing credentials. You can also use existing groups and user accounts to secure access to resources. These features provide a smoother lift-and-shift of on-premises resources to Azure.
----
Source: https://learn.microsoft.com/en-us/azure/active-directory-domain-services/overview

TIP: Have a look at https://azure.microsoft.com/en-us/pricing/details/active-directory/[Azure Active Directory (Azure AD) pricing] before going with this option

=== Links

- https://www.youtube.com/watch?v=LYF-NLHD2uQ
- https://learn.microsoft.com/en-us/answers/questions/270527/how-to-map-import-users-from-azure-to-keycloak-(-w
    * https://playbook.stakater.com/content/workshop/aad-in-openshift.html[Adding Azure Active Directory Users to KeyCloak]
    * https://suryaprakash-pandey.medium.com/azure-ad-idp-with-keycloak-as-sp-1ca933d71388#
    * https://stackoverflow.com/questions/54823058/keycloak-integration-with-azure-ad-for-webapp-authentication
- https://blog.hcltechsw.com/versionvault/how-to-configure-microsoft-azure-active-directory-as-keycloak-identity-provider-to-enable-single-sign-on-for-hcl-compass/
- https://azure.microsoft.com/en-us/pricing/details/active-directory/

== Apache Directory Server

----
ApacheDS is focused on being a little easier to install, configure, and manage. The accompanying Apache Directory Studio suite of tools is there for IT admins to more easily implement ApacheDS. The UI tools include an LDAP schema editor, LDAP browser, LDIF editor, access control editor, and more. The ApacheDS and associated tools have largely been written in Java.

A core distinction that Apache Directory Server has when compared to OpenLDAP and other LDAP-based, open-source solutions has been that ApacheDS has introduced stored procedures and triggers to help make database maintenance and the process of managing the database a little stronger.
----
Source: https://jumpcloud.com/blog/apache-directory-server[What is Apache Directory™ Server? – ApacheDS]


== OpenLDAP

----
OpenLDAP is command-line driven software that allows IT admins to build and manage an LDAP directory. Due to its minimal UI and reliance on the CLI, it requires an in-depth knowledge of the LDAP protocol and directory structure.
----
Source : https://jumpcloud.com/blog/what-is-openldap[What Is OpenLDAP?]

=== Links

- https://www.openldap.org/doc/admin26/quickstart.html[A Quick-Start Guide]

== 389 Directory Server

----
Yet another incarnation of LDAP, 389 Directory Server, run by RedHat, is focused on being a reasonably high-performance version of the protocol. 389 Directory Server is open source and shares many similarities with OpenLDAP. And, like OpenLDAP, it works best with Linux and requires significant technical knowledge to implement and manage.
----
Source: https://jumpcloud.com/blog/choosing-ldap-server

=== Links

- https://www.linkedin.com/pulse/getting-started-open-source-identity-access-keycloak-sureshkumar[Getting Started with Open Source Identity Access Management (Keycloak) and Open Source Directory Service (389 Directory Server)]
- https://awslife.medium.com/configuration-the-keycloak-server-for-sso-single-sign-on-for-a-lab-environment-2-428dc878ba3e[Configuration the keycloak server for SSO(Single-Sign-On) for a lab environment (2)]

== FreeIPA

----
FreeIPA is focused on managing Linux users and hosts. FreeIPA is a combination of LDAP, Kerberos, DNS, and more. However, FreeIPA is rarely used on its own. Much like Samba, FreeIPA is often leveraged in conjunction with Active Directory or other IAM solutions. So, FreeIPA doesn’t have a reputation for being a standalone directory service.
----
Source: https://jumpcloud.com/blog/open-source-active-directory
